server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://auth/hello
          predicates:
            - Path=/hello/**
